### ISSUE TITLE
Select SDH if you have to choose between SDH and Forced.

### ISSUE THREAD

**Issue by AziRizvi** [pzim-devdata/mpv-scripts#1]
Would you mind adding this to the script that if you're playing a file and that file has two subtitle streams, Forced and SDH subtitles, in that case the script should always choose the SDH ones?

Feel free to close this if you think that this is irrelevant or something.

Thanks.

**Comment by pzim-devdata** [comment]
```
function select_sdh_subtitle()
    local sdh_sub = nil
    for i, sub in ipairs(mp.get_property_native("track-list")) do
        if sub.type == "sub" and sub.title ~= nil and sub.title:lower():find("sdh") then
            if sdh_sub == nil or sub.forced then
                sdh_sub = sub
            end
        end
    end
    if sdh_sub then
        mp.set_property("sid", sdh_sub.id)
    end
end

mp.register_event("file-loaded", select_sdh_subtitle)
```
Let me know if it's what you wanted

**Comment by AziRizvi** [comment]
> ```
> function select_sdh_subtitle()
>     local sdh_sub = nil
>     for i, sub in ipairs(mp.get_property_native("track-list")) do
>         if sub.type == "sub" and sub.title ~= nil and sub.title:lower():find("sdh") then
>             if sdh_sub == nil or sub.forced then
>                 sdh_sub = sub
>             end
>         end
>     end
>     if sdh_sub then
>         mp.set_property("sid", sdh_sub.id)
>     end
> end
> 
> mp.register_event("file-loaded", select_sdh_subtitle)
> ```
> 
> Let me know if it's what you wanted

I am sorry but not quite, please let me explain.
Let's say you're dealing with a file that has 3 subtitle streams, a regular subtitle stream, an SDH one and a Forced one, the default script behaviour is that it prevents SDH or Forced subtitle streams from being selected when a file is launched, correct?
So when the file is launched, the third regular stream will be selected.

I want that default behaviour to remain as is, but say for example that I'm playing a file that only has two subtitle streams, a forced one and an SDH one, in that situation, currently, the forced stream gets selected, I want to prevent that and instead make the SDH stream get selected ONLY in that specific situation when a regular stream is not available.

**Comment by pzim-devdata** [comment]
```
function select_not_forced_subtitle()
    local last_sub = nil
    local sdh_sub = nil
    
    for i, sub in ipairs(mp.get_property_native("track-list")) do
        if sub.type == "sub" and not sub.forced then
            if sub.title == nil or (not sub.title:find("SDH") and not string.lower(sub.title):find("force")) then
                last_sub = sub
            elseif sub.title:lower():find("sdh") then
                sdh_sub = sub
            end
        end
    end
    
    if last_sub then
        mp.set_property("sid", last_sub.id)
    elseif sdh_sub then
        mp.set_property("sid", sdh_sub.id)
    end
end

mp.register_event("file-loaded", select_not_forced_subtitle)
```

The purpose of this script is to automatically select the appropriate subtitle track when a video file is loaded in the MPV media player. The script prioritizes the selection of non-forced subtitles, but also handles the case where the only available subtitle options are a forced subtitle and an SDH (Subtitles for the Deaf and Hard of Hearing) subtitle.

Here's how the script works:

1. When a new video file is loaded, the `select_not_forced_subtitle()` function is called.
2. The script iterates through the available subtitle tracks in the video.
3. It first looks for the last non-forced subtitle track, excluding any tracks that have "SDH" or "force" in the title (case-insensitive).
4. If a non-forced, non-SDH subtitle track is found, it is selected as the active subtitle.
5. However, if the only available subtitle tracks are a forced subtitle and an SDH subtitle, the script will select the SDH subtitle, even if it is marked as forced.

This behavior ensures that the default preference for non-forced subtitles is preserved, but also handles the specific case where the only choices are a forced subtitle and an SDH subtitle. In this scenario, the script will select the SDH subtitle, as this is likely to provide the best experience for the user.

The key aspects of the script are:

- It maintains the original logic of selecting the last non-forced, non-SDH subtitle.
- It adds an additional check to select the SDH subtitle if it's the only option available, even if it's marked as forced.
- This ensures that the SDH subtitle is used when appropriate, while still prioritizing non-forced subtitles by default.

Please let me know if you have any other questions about the functionality of this script.

Try it and let me know ;-)

**Comment by AziRizvi** [comment]
> ```
> function select_not_forced_subtitle()
>     local last_sub = nil
>     local sdh_sub = nil
>     
>     for i, sub in ipairs(mp.get_property_native("track-list")) do
>         if sub.type == "sub" and not sub.forced then
>             if sub.title == nil or (not sub.title:find("SDH") and not string.lower(sub.title):find("force")) then
>                 last_sub = sub
>             elseif sub.title:lower():find("sdh") then
>                 sdh_sub = sub
>             end
>         end
>     end
>     
>     if last_sub then
>         mp.set_property("sid", last_sub.id)
>     elseif sdh_sub then
>         mp.set_property("sid", sdh_sub.id)
>     end
> end
> 
> mp.register_event("file-loaded", select_not_forced_subtitle)
> ```
> 
> The purpose of this script is to automatically select the appropriate subtitle track when a video file is loaded in the MPV media player. The script prioritizes the selection of non-forced subtitles, but also handles the case where the only available subtitle options are a forced subtitle and an SDH (Subtitles for the Deaf and Hard of Hearing) subtitle.
> 
> Here's how the script works:
> 
> 1. When a new video file is loaded, the `select_not_forced_subtitle()` function is called.
> 2. The script iterates through the available subtitle tracks in the video.
> 3. It first looks for the last non-forced subtitle track, excluding any tracks that have "SDH" or "force" in the title (case-insensitive).
> 4. If a non-forced, non-SDH subtitle track is found, it is selected as the active subtitle.
> 5. However, if the only available subtitle tracks are a forced subtitle and an SDH subtitle, the script will select the SDH subtitle, even if it is marked as forced.
> 
> This behavior ensures that the default preference for non-forced subtitles is preserved, but also handles the specific case where the only choices are a forced subtitle and an SDH subtitle. In this scenario, the script will select the SDH subtitle, as this is likely to provide the best experience for the user.
> 
> The key aspects of the script are:
> 
> * It maintains the original logic of selecting the last non-forced, non-SDH subtitle.
> * It adds an additional check to select the SDH subtitle if it's the only option available, even if it's marked as forced.
> * This ensures that the SDH subtitle is used when appropriate, while still prioritizing non-forced subtitles by default.
> 
> Please let me know if you have any other questions about the functionality of this script.
> 
> Try it and let me know ;-)

Thank you so much for the detailed explanation, I appreciate it.
I tried out the code and this gets me exactly what I was looking for, cheers.

Thank you!
